### ISSUE TITLE
9 in 1 issue

### ISSUE THREAD

**Issue by NoriSilverrage** [alkcorp/GTplusplus#495]
# Issue Title  
The 9 in 1 appears to not be working

## Expected Behavior
It forms correctly, but will not run.

## Current Behavior
I made the multi with input/output busses, a muffler, maint hatch and a IV energy hatch.
Putting a circuit of 20 in a input bus and a bunch of compressible silicon yields nothing. Changing the mode to Misc and trying a laser recipe also never turns on.

Thinking I may need a input/output hatch for it to run, I add those. In metal mode it still doesn't work and when I attempt to switch to another mode I get a error and lose connection to the server with the following error:
`
[08:35:25] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:61338
java.lang.NullPointerException
        at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.resetRecipeMapFo
rHatch(GregtechMeta_MultiBlockBase.java:1615) ~[GregtechMeta_MultiBlockBase.class:?]
        at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.resetRecipeMapFo
rAllInputHatches(GregtechMeta_MultiBlockBase.java:1579) ~[GregtechMeta_MultiBlockBase.class:?]
        at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.resetRecipeMapFo
rAllInputHatches(GregtechMeta_MultiBlockBase.java:1573) ~[GregtechMeta_MultiBlockBase.class:?]
        at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onScrewdriverRig
htClick(GregtechMeta_MultiBlockBase.java:1631) ~[GregtechMeta_MultiBlockBase.class:?]
        at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1318) ~[BaseMetaTileEntit
y.class:?]
        at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:307) ~[GT_Block_Machines.class:
?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[08:35:25] [Server thread/INFO]: Nori_Silverrage lost connection: TextComponent{text='Internal server error', siblings=[
], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, h
overEvent=null}}
`

**Comment by NoriSilverrage** [comment]
Ok did some more testing. It doesn't like input hatches. Anytime I try to change the mode with a input hatch installed it kicks me from the server.

I did get it to work with no fluid inputs however as I discovered you need a circuit in all inputs whether or not they are used.

**Comment by kekzdealer** [comment]
I can confirm that the 9-1 does not like input hatches at all. 
Even when putting a correct circuit in the input hatch it still does not work.

**Comment by Anarack** [comment]
9 - 1 does work with input hatches, or at least the autoclave mode does work, and as I'm not sure when/if it was fixed all input buses need a circuit in order for the machine to work.

**Comment by kekzdealer** [comment]
If the machine is in mode C already, hatches can be added as long as that prerequisite is met and the mode is not changed.

**Comment by botn365** [comment]
i have tested the 9 in 1 on version: GTplusplus-DevTop-draknyte1-385
 but the game still crashes when changing the changing the mode when there is a input hatch
