### ISSUE TITLE
Charcoal pile igniter doesn't work

### ISSUE THREAD

**Issue by quedral** [alkcorp/GTplusplus#606]
# Issue Title  
 As title suggests it doesn't work

## Expected Behavior
I was expecting it to work?

## Current Behavior
it doesnt turn logs into charcoal
steps i took:

step 1
make 3x1x3 bricks

step 2
put 3x3x3 on top of bricks

step 3
cover every side of oak log with dirt except very top center

step 4
place charcoal pile igniter on top center

step 5
nothing happens. no texture change indicating its working. portable scanner says machine inactive

waila says its running fine 0/0

i even whacked it few time with soft mallet after waiting like 3-5 minutes. doesn't change anything.

I have included some parts of gregtech.log: https://pastebin.com/P2Wq2A3x

hope it helps

## Possible Solution
I have no idea

## Steps to Reproduce (for bugs)
check current behaviour

## Context
The issue doesn't effect me at all. Reporting the bug as moronmachinegun suggested.

## Game Environment
GTNH 2.0.8.1

If not using a modpack:
GTNH 2.0.8.1

Also include:
GTNH 2.0.8.1 
Java version 1.8.0_231
Windows 10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [ x]    Single Player?
 - [ x]    Multi Player?

**Comment by chochem** [comment]
Can confirm. This is GT-PlusPlus-1.7.04.449, btw. Last confirmed working for me was in GTNH 2.0.8.0b. Not sure about pre1-4, I think it might already have been broken there.

Pic:

![2020-01-11_21 32 32](https://user-images.githubusercontent.com/40274384/72210952-9f560e80-34ba-11ea-89af-b0a6f82172d5.png)

**Comment by chochem** [comment]
Gregtech.log has many iterations of the following error:

java.lang.NoSuchMethodError: gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_Charcoal_Pit.isWoodLog(Lnet/minecraft/block/Block;I)Z
	at gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_Charcoal_Pit.checkRecursiveBlocks(GT_MetaTileEntity_Charcoal_Pit.java:106)
	at gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_Charcoal_Pit.checkRecipe(GT_MetaTileEntity_Charcoal_Pit.java:79)
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:292)
	at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:527)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at fastcraft.at.a(F:978)
	at fastcraft.H.aq(F:36)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
