### ISSUE TITLE
Toxic Everglades mobs cause crash with special mobs

### ISSUE THREAD

**Issue by Mogball** [alkcorp/GTplusplus#639]
# Toxic everglades mobs cause crash with special mobs

## Expected Behavior
At the very least, the server should not crash. Better yet, GT++ everglades mobs should have special mobs!

## Current Behavior
```
java.lang.NullPointerException: Ticking entity
	at toast.specialMobs.entity.EntitySpecialFishHook.onImpact(EntitySpecialFishHook.java:190)
	at toast.specialMobs.entity.EntitySpecialFishHook.func_70071_h_(EntitySpecialFishHook.java:150)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
```
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at toast.specialMobs.entity.pigzombie.EntityFishingPigZombie.func_70785_a(EntityFishingPigZombie.java:99)
	at net.minecraft.entity.EntityCreature.func_70626_be(SourceFile:63)
	at toast.specialMobs.entity.pigzombie.Entity_SpecialPigZombie.func_70626_be(Entity_SpecialPigZombie.java:118)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1780)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
	at toast.specialMobs.entity.pigzombie.Entity_SpecialPigZombie.func_70636_d(Entity_SpecialPigZombie.java:138)
	at toast.specialMobs.entity.pigzombie.EntityFishingPigZombie.func_70636_d(EntityFishingPigZombie.java:90)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
	at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
	at net.minecraft.entity.monster.EntityPigZombie.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
	at toast.specialMobs.Properties.getBoolean(Properties.java:302)
	at toast.specialMobs.Properties.getBoolean(Properties.java:291)
	at toast.specialMobs.entity.EntitySpecialFishHook.<clinit>(EntitySpecialFishHook.java:21)
```

## Possible Solution
Seems like some special mobs-specific things are not implemented.

## Steps to Reproduce (for bugs)
 1. Go to toxic everglades
 2. Be next to a toxic everglades mob
 3. Server crashes with nullptr exception

## Context
Can't explore everglades :(

## Game Environment
 * Modpack Name:  GregTech new horizons
 * Version used: 2.0.8.4

Also include:
 * Gregtech version: `gregtech-5.09.33.31`
 * IC2 version: `industrialcraft-2-2.2.828a-experimental`
 * Java version: Open_J9 1.8.0_242
 * Operating System: Windows 10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
GTNH issue, already fixed there.

**Comment by draknyte1** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/5584
